# Copyright (c) Microsoft. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

language: generic
branches:
  only:
    - master
env:
  global:
    - IDE_VERSION=1.8.1
  matrix:
    - BOARD="esp8266:esp8266:nodemcuv2:xtal=80,eesz=4M3M"
before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - sleep 3
  - export DISPLAY=:1.0
  - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
  - tar xf arduino-$IDE_VERSION-linux64.tar.xz
  - mv arduino-$IDE_VERSION $HOME/arduino-ide
  - export PATH=$PATH:$HOME/arduino-ide
  - if [[ "$BOARD" =~ "arduino:samd:" ]]; then
      arduino --install-boards arduino:samd;
      arduino --install-library WiFi101;
      arduino --install-library RTCZero;
      arduino --install-library NTPClient;
    fi
  - if [[ "$BOARD" =~ "esp8266:esp8266:" ]]; then
      arduino --pref "boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json" --install-boards esp8266:esp8266;
      arduino --pref "boardsmanager.additional.urls=" --save-prefs;
      arduino --install-library NTPClient;
      arduino --install-library NTPClient;
    fi
  - findAndReplace() { sed -i'' -e"s|$1|$2|g" "$3"; }
  - buildExampleSketch() {
      EXAMPLE_SKETCH=$PWD/source/$1/$1.ino;


      
      arduino --verbose-build --verify --board $BOARD $EXAMPLE_SKETCH;
    }
install:
  - cp -r $PWD/source/libraries/* /home/travis/Arduino/libraries/

script:
  - buildExampleSketch Sniffer
